#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
PROJECT_ROOT=$(realpath "${DIR}/../..")

changed_tf_files=$(git status --porcelain | awk '/.tf/ { print $2; }')

if [[ -z ${changed_tf_files} ]]; then
  # No TF files changed... nothing to do.
  exit 0
fi

if ! command -v terraform-docs >/dev/null; then
  echo "please install terrafrom-docs"
  echo "brew install terraform-docs"
  exit 1
fi

tf_modules=$(for f in ${changed_tf_files}; do dirname ${f}; done | uniq)

echo "checking terraform docs"

${PROJECT_ROOT}/scripts/pre-commit-generate-docs.sh ${tf_modules}

if [ $? -gt 0 ]; then
  echo "Files updated: ${files_updated}"
  exit 1
else
  echo "All up to date"
fi
